services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.production
  db:
    env_file:
      - ./.env.production
